baseDir: /home/vijayrc/Projs/VRC5/dash/sample-base
sslTruststore: /home/vijayrc/Projs/VRC5/dash/sample-base/some.jks
sslTruststorePassword: XXXX
sources:
  - name: elastic1
    link: http://localhost:9200/_nodes/stats/os,process,jvm,fs,indices?pretty
    poll: 2
    duration: 7200
    flatten: true
categories:
  - name: memory
    unit: bytes
    fields: os.mem.free_in_bytes, os.mem.used_in_bytes, jvm.mem.heap_committed_in_bytes, jvm.mem.heap_used_in_bytes
  - name: percentage-usage
    unit: percentage-usage
    fields: os.mem.free_percent, os.mem.used_percent, os.cpu.usage, process.cpu.percent
  - name: threads-count
    unit: count-of-threads
    fields: jvm.threads.count, jvm.threads.peak_count
  - name: disk_io_ops
    unit:  ops counts
    fields: fs.data.0.disk_writes, fs.data.0.disk_reads, fs.data.0.disk_io_op
  - name: disk_io_bytes
    unit: bytes
    fields: fs.data.0.disk_read_size_in_bytes, fs.data.0.disk_write_size_in_bytes
  - name: index_counts
    unit: counts
    fields: search.query_total, search.fetch_total, indexing.index_total
  - name: index_times
    unit: time in millisecond
    fields: search.query_time_in_millis,search.fetch_time_in_millis,merges.total_time_in_millis,refresh.total_time_in_millis,flush.total_time_in_millis
  - name: query_cache
    unit: count
    fields: query_cache.hit_count,query_cache.miss_count,query_cache.evictions
